import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useDreamStore } from '../store/dreamStore'
import LanguageSelector from '../components/LanguageSelector'

export default function Report() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { dreamResult } = useDreamStore()
  const [report, setReport] = useState<string>('')

  useEffect(() => {
    if (!dreamResult) {
      navigate('/result')
      return
    }

    // Generate comprehensive report
    const generateReport = () => {
      const reportSections = [
        `# Soul Message Report\n\n`,
        `## Dream Essence\n${dreamResult.essence}\n\n`,
        `## Detailed Analysis\n${dreamResult.deepInsight}\n\n`,
        `## Key Symbols\n${dreamResult.symbols.map(s => `- ${s.emoji} **${s.name}**: ${s.meaning}`).join('\n')}\n\n`,
        `## Actionable Guidance\n${dreamResult.advice.map((a, i) => `${i + 1}. ${a}`).join('\n')}\n\n`,
        `## Spiritual Message\n${dreamResult.spiritualMessage}\n\n`,
        `## 7-Day Guidance\n\n`,
        `### Day 1-2: Reflection\nTake time to reflect on the symbols and messages from your dream. Journal about any emotions or memories it triggered.\n\n`,
        `### Day 3-4: Integration\nBegin to integrate the insights into your daily life. Pay attention to synchronicities and signs.\n\n`,
        `### Day 5-7: Action\nTake concrete steps based on the advice provided. Trust your intuition and the guidance you've received.\n\n`,
        `---\n*Generated by ONEIRO — AI Dream Interpreter & Soul Guide*`,
      ]

      setReport(reportSections.join(''))
    }

    generateReport()
  }, [dreamResult, navigate])

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `soul-report-${new Date().toISOString().split('T')[0]}.md`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleShare = () => {
    if (window.Telegram?.WebApp?.openLink) {
      const shareText = `My Soul Message Report from ONEIRO 🌙\n\n${dreamResult?.essence}`
      window.Telegram.WebApp.openLink(
        `https://t.me/share/url?url=${encodeURIComponent(shareText)}`
      )
    }
  }

  if (!dreamResult) return null

  return (
    <div className="min-h-screen bg-gradient-midnight p-6">
      <div className="max-w-2xl mx-auto">
        {/* Language Selector */}
        <div className="flex justify-end mb-4">
          <LanguageSelector />
        </div>
        <div className="card mb-6">
          <h1 className="text-2xl font-title font-bold text-white mb-4">
            📜 Soul Message Report
          </h1>
          <div className="prose prose-invert max-w-none">
            <pre className="whitespace-pre-wrap text-text-primary font-mono text-sm bg-secondary p-6 rounded-lg overflow-auto max-h-[600px]">
              {report}
            </pre>
          </div>
        </div>

        <div className="flex gap-4">
          <button onClick={handleDownload} className="btn-primary flex-1">
            Download Report
          </button>
          <button onClick={handleShare} className="btn-primary flex-1">
            {t('result.share')}
          </button>
        </div>

        <button
          onClick={() => navigate('/dream')}
          className="btn-primary w-full mt-4"
        >
          {t('visualize.another')}
        </button>
      </div>
    </div>
  )
}
